Preprocessing for *covid_19_data.csv*

In [13]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [14]:
covid_df = pd.read_csv("./data/covid_19_data.csv")

In [15]:
covid_df.head(10)

,SNo,ObservationDate,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
0,1,01/22/2020,Anhui,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
1,2,01/22/2020,Beijing,Mainland China,1/22/2020 17:00,14.0,0.0,0.0
2,3,01/22/2020,Chongqing,Mainland China,1/22/2020 17:00,6.0,0.0,0.0
3,4,01/22/2020,Fujian,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
4,5,01/22/2020,Gansu,Mainland China,1/22/2020 17:00,0.0,0.0,0.0
5,6,01/22/2020,Guangdong,Mainland China,1/22/2020 17:00,26.0,0.0,0.0
6,7,01/22/2020,Guangxi,Mainland China,1/22/2020 17:00,2.0,0.0,0.0
7,8,01/22/2020,Guizhou,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
8,9,01/22/2020,Hainan,Mainland China,1/22/2020 17:00,4.0,0.0,0.0
9,10,01/22/2020,Hebei,Mainland China,1/22/2020 17:00,1.0,0.0,0.0

In [16]:
df = covid_df

In [17]:
#process datetime
df['ObservationDate'] = pd.to_datetime(df['ObservationDate'])

In [18]:
#drop columns Last Update
df.drop(columns = 'Last Update',inplace = True)

In [19]:
df.isna().sum()

SNo                    0
ObservationDate        0
Province/State     26449
Country/Region         0
Confirmed              0
Deaths                 0
Recovered              0
dtype: int64

In [20]:
#Active Cases
df['Active'] = df.Confirmed - df.Deaths - df.Recovered

In [23]:
df

,SNo,ObservationDate,Province/State,Country/Region,Confirmed,Deaths,Recovered,Active
0,1,2020-01-22,Anhui,Mainland China,1.0,0.0,0.0,1.0
1,2,2020-01-22,Beijing,Mainland China,14.0,0.0,0.0,14.0
2,3,2020-01-22,Chongqing,Mainland China,6.0,0.0,0.0,6.0
3,4,2020-01-22,Fujian,Mainland China,1.0,0.0,0.0,1.0
4,5,2020-01-22,Gansu,Mainland China,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...
77462,77463,2020-08-01,Zaporizhia Oblast,Ukraine,800.0,21.0,597.0,182.0
77463,77464,2020-08-01,Zeeland,Netherlands,867.0,69.0,0.0,798.0
77464,77465,2020-08-01,Zhejiang,Mainland China,1270.0,1.0,1268.0,1.0
77465,77466,2020-08-01,Zhytomyr Oblast,Ukraine,1896.0,37.0,1485.0,374.0
77466,77467,2020-08-01,Zuid-Holland,Netherlands,13262.0,1311.0,0.0,11951.0

In [11]:
#save to csv file (option)
df.to_csv('Data_preprocessed.csv')